version: "3.9"
services:

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
      DB_HOST: db
      DB_PORT: 5432

  tests:
    build:
      context: ./tests
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    depends_on:
      - app

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  celery-worker:
    build: ./app
    command: celery -A celery_app worker --loglevel=info
    depends_on:
      - redis
      - db
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

volumes:
  db_data: